### PR TITLE
Reusable signup questionnaire form components

### PR DESCRIPTION
**Pull request by tjay22**
- The signup questionnaire is dynamically created from a JSON object
- Questions can be added or removed easily
- Form fields are separated into their own components 
- router.refresh() removed from logout button on Navbar

### CODE REVIEW

**Comment by tjay22** [comment]
@ogeeDeveloper @Ragudos @KQuiggins @mikebashford - Would love to get a code review from any of you guys as I'm still new to Typescript and React Hook Form.

**Comment by Ragudos** [comment]
> @ogeeDeveloper @Ragudos @KQuiggins @mikebashford - Would love to get a code review from any of you guys as I'm still new to Typescript and React Hook Form.

I have commented on code that can be changed. Is it not visible on your end?

**Comment by tjay22** [comment]
> > @ogeeDeveloper @Ragudos @KQuiggins @mikebashford - Would love to get a code review from any of you guys as I'm still new to Typescript and React Hook Form.
> 
> I have commented on code that can be changed. Is it not visible on your end?

@Ragudos I don't see the comments on my end

**Comment by Ragudos** [comment]
image

**Comment by tjay22** [comment]
> I added review comments which should be visible on your end. Hmm.

That is so strange...

However, I can read your comments from the screenshot and I can make the changes. I did delete the input-radio component already.

**Comment by Ragudos** [comment]
> > I added review comments which should be visible on your end. Hmm.
> 
> That is so strange...
> 
> However, I can read your comments from the screenshot and I can make the changes. I did delete the input-radio component already.

That would be tiresome to read. Have you checked the reviews section if there's any?

**Comment by tjay22** [comment]
> That would be tiresome to read. Have you checked the reviews section if there's any?

=( Nothing...

image

**Comment by tjay22** [comment]
@Ragudos I'm not sure why I can't see the reviews but I made the changes based on the screenshot you sent =)

**Comment by Ragudos** [comment]
> @Ragudos I'm not sure why I can't see the reviews but I made the changes based on the screenshot you sent =)

Thank you. I will check them shortly.

**Review by hinode-codes — APPROVED** [review]

**Pull request merged**
