### PR TITLE
Add [feature] landing page. Fixes issue #14

### PR DESCRIPTION
**Pull request by tjay22**
Fixes issue [#14](https://github.com/Software-Developer-Academy/mentor-match/issues/14).

- Landing page created
- File project structure organized (created and moved styles folder to src folder)
- Added icons and images
- Added Shadcn components (Carousel, Drawer, NavigationMenu, Separator)
- Added static data folders
- Added following components, Navbar, Footer, RatingStars

### CODE REVIEW

**Comment by coltonehrman** [comment]
@tjay22 Can you update your branch with main and resolve the merge conflicts please

**Comment by tjay22** [comment]
> @tjay22 Can you update your branch with main and resolve the merge conflicts please

Conflicts have been resolved

**Comment by coltonehrman** [comment]
@tjay22 Now check the CI errors and please resolve those as well :)

**Comment by tjay22** [comment]
> @tjay22 Now check the CI errors and please resolve those as well :)

Done :)

**Review by coltonehrman — APPROVED** [review]

**Pull request merged**
