### PR TITLE
Feature/account questionnaire

### PR DESCRIPTION
**Pull request by SaudAhmed96**
created /account-questionnaire page.

This page has a carousel that will go through each of the questions. <AccountQuestion1/> is a component I created that has one question, the other components will need to be created in separate ticket I think we discussed and other people can create some question components to fill in each page of carousel. 

Note:  Design does not match 100% as I think we need a background image, since rounded border does not give same affect. Also currently SKIP button does not route to anywhere we will need to consider where we want to route to (i.e. home page?). Design is not responsive, looks best in desktop mode right now. 

image

### CODE REVIEW

**Comment by coltonehrman** [comment]
@SaudAhmed96 Please format your code

**Comment by SaudAhmed96** [comment]
Hey @coltonehrman, i have been trying for like 30 min straight looking this issue up. I have always had some issues with my VS Code editor. I am not sure what to do maybe i can touch base with you sometime this week to resolve it.

**Comment by Ragudos** [comment]
Can you run

```bash
npm run format
```

**Comment by Ragudos** [comment]
Also, please adhere to the "common" format for commit messages, so we can easily follow what you added and such. For example:

"format code"
"fix lint errors"
"add feature"

And then you can reference an issue:

"add feature, closes issue <number of issue, e.g. #0>"

**Review by coltonehrman — APPROVED** [review]
@SaudAhmed96 LGTM! I will go ahead and merge and open up tickets for next set of tasks. Thank you :)

**Pull request merged**
