### PR TITLE
Add Contributors

### PR DESCRIPTION
**Pull request by donlevans29**

### CODE REVIEW

**Comment by donlevans29** [comment]
@all-contributors please add @tjay22 for code

**Comment by donlevans29** [comment]
More context for this submission.
I'm so new to this so sorry if I'm doing something wrong.

I was following -> https://javascript.plainenglish.io/how-to-add-github-contributors-to-readme-2affcda57dcc
I was able to duplicate on another project -> https://github.com/donlevans29/Code-Skill-Tracker
image

I'm using a bot on my github account that adds contributors using this syntax
@all-contributors please add @<username> for <contributions>

**Comment by coltonehrman** [comment]
This looks cool @donlevans29 ! I haven't don't this before either so not sure lol

Will take a closer look once I get into the office

**Comment by coltonehrman** [comment]
@donlevans29 I'm not sure if this works or not? Looking at the rich diff, it doesn't show anything.

**Comment by coltonehrman** [comment]
@donlevans29 Ok, I just added the @allcontributors bot to the repo.

**Comment by coltonehrman** [comment]
https://github.com/all-contributors please add @tjay22 for code
https://github.com/all-contributors please add @coltonehrman for code
https://github.com/all-contributors please add @mikebashford for code
https://github.com/all-contributors please add @donlevans29 for review

**Comment by coltonehrman** [comment]
@all-contributors please add @tjay22 for code
@all-contributors please add @coltonehrman for code
@all-contributors please add @mikebashford for code
@all-contributors please add @donlevans29 for review

**Comment by coltonehrman** [comment]
@all-contributors please add @coltonehrman for code

**Comment by coltonehrman** [comment]
It seems we just need to submit 1 line comments now for each contributor

**Comment by coltonehrman** [comment]
https://github.com/all-contributors please add @coltonehrman for code

**Comment by coltonehrman** [comment]
@all-contributors please add @coltonehrman for code

**Comment by coltonehrman** [comment]
@all-contributors please add @coltonehrman for code

**Comment by coltonehrman** [comment]
@all-contributors please add @mikebashford for code

**Comment by coltonehrman** [comment]
@all-contributors please add @mikebashford for code

**Comment by coltonehrman** [comment]
@all-contributors please add @coltonehrman for code

**Comment by coltonehrman** [comment]
@all-contributors please add @Ragudos for code

**Comment by coltonehrman** [comment]
@all-contributors please add @reuterShawn for code

**Comment by coltonehrman** [comment]
@all-contributors please add @reuterShawn for code

**Comment by coltonehrman** [comment]
@all-contributors please add @kalpeshdhotre  for code

**Comment by coltonehrman** [comment]
@all-contributors please add @ogeeDeveloper for code

**Comment by coltonehrman** [comment]
@all-contributors please add @harunugurlu for code

**Comment by coltonehrman** [comment]
@all-contributors please add @SaudAhmed96 for code

**Comment by coltonehrman** [comment]
@all-contributors please add @icarodredd for code

**Comment by coltonehrman** [comment]
@all-contributors please add @KQuiggins for code

**Comment by coltonehrman** [comment]
@donlevans29 Ok, I think I added everyone. I guess we can close this PR out now. Would be good to include a README sections about how to add contributor using the bot.

**Comment by coltonehrman** [comment]
@all-contributors please add @coltonehrman for project management and review and ideas

**Comment by SunilKumar-K** [comment]
We can do this with `github  actions`, If you are okay this then i can't do anything @coltonehrman. or else I want to work on this  issue by using `github actions`, I can do soo..

**Comment by coltonehrman** [comment]
> We can do this with `github  actions`, If you are okay this then i can't do anything @coltonehrman. or else I want change this  with  `github actions`, I can do soo..
> 
>  

That would be cool! Feel free to open an issue or PR with the changes. Thank you

**Pull request closed without merging**
